CREATE DATABASE /*!32312 IF NOT EXISTS*/ `go-mvc` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `go-mvc`;

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password CHAR(60) NOT NULL,
    phone VARCHAR(20) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS `notes`;

CREATE TABLE `notes` (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    comments TEXT NOT NULL,
    user_id INT(10) UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);